version: '3.1'

services:
  building1:
    image: volttron/volttron:tcc
    container_name: building1
    hostname: building1
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22911:22916
      # ssl port for web
      - 8441:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
    volumes:
      - ./platform_configs/building1:/home/volttron/configs
      - ./platform_configs/building1/building1_config.yml:/platform_config.yml
    networks:
      tcc_network:
        ipv4_address: 172.28.5.1
#    volumes:
      #change the following to map to the respective configs
#       - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
#       - ./log/:/code/volttron/volttron/log
#       - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
#       - ./source/bcvtb:/home/volttron/volttron/bcvtb
#    command: bash upgrade-scripts/upgrade-b1-tns

  smalloffice:
    volumes:
       - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
       - ./log/:/home/volttron/volttron/log
       - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
       - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
       - ./source/bcvtb:/home/volttron/volttron/bcvtb
    build:
      context: .
      args:
        buildings: smalloffice
    command: bash upgrade-scripts/upgrade-sm-tns

  largeoffice:
    volumes:
       - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
       - ./log/:/home/volttron/volttron/log
       - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
       - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
       - ./source/bcvtb:/home/volttron/volttron/bcvtb
    build:
      context: .
      args:
        buildings: largeoffice
    command: bash upgrade-scripts/upgrade-lo-tns

  brsw:
      volumes:
         - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
         - ./log/:/home/volttron/volttron/log
         - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
         - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
         - ./source/bcvtb:/home/volttron/volttron/bcvtb
      build:
        context: .
        args:
          buildings: brsw
      command: bash upgrade-scripts/upgrade-brsw-tns

  central:
    image: volttron/volttron:tcc
    container_name: central
    hostname: central
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22915:22916
      # ssl port for web
      - 8445:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
    volumes:
      - ./platform_configs/central:/home/volttron/configs
      - ./platform_configs/central/central_platform_config.yml:/platform_config.yml
    networks:
      tcc_network:
        ipv4_address: 172.28.5.5

#      - ./transactivecontrol/TNS/:/home/volttron/volttron/config/
#      - ./log/:/home/volttron/volttron/log
#      - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
#      - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
#      - ./source/bcvtb:/home/volttron/volttron/bcvtb
#    build:
#      context: .
#      args:
#        buildings: campus_city
#    command: bash upgrade-scripts/upgrade-tns

networks:
  tcc_network:
    name: tcc_network
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         ip_range: 172.28.5.0/24