version: '3.1'

services:
  building1_alone:
    network_mode: host
    volumes:
       - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
       - ./log/:/home/volttron/volttron/log
       - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
       - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
       - ./source/bcvtb:/home/volttron/volttron/bcvtb
    build:
      context: .
      args:
        buildings: building1
    working_dir: /home/volttron/volttron/
    command: bash upgrade-scripts/upgrade-b1-tns

  smalloffice_alone:
    network_mode: host
    volumes:
       - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
       - ./log/:/home/volttron/volttron/log
       - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
       - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
       - ./source/bcvtb:/home/volttron/volttron/bcvtb
    build:
      context: .
      args:
        buildings: smalloffice
    working_dir: /home/volttron/volttron/
    command: bash upgrade-scripts/upgrade-sm-tns

  largeoffice_alone:
    network_mode: host
    volumes:
       - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
       - ./log/:/home/volttron/volttron/log
       - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
       - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
       - ./source/bcvtb:/home/volttron/volttron/bcvtb
    build:
      context: .
      args:
        buildings: largeoffice
    working_dir: /home/volttron/volttron/
    command: bash upgrade-scripts/upgrade-lo-tns

  brsw_alone:
      network_mode: host
      volumes:
         - ./transactivecontrol/MarketAgents/:/home/volttron/volttron/config/
         - ./log/:/home/volttron/volttron/log
         - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
         - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
         - ./source/bcvtb:/home/volttron/volttron/bcvtb
      build:
        context: .
        args:
          buildings: brsw
      working_dir: /home/volttron/volttron/
      command: bash upgrade-scripts/upgrade-brsw-tns

  central:
    image: volttron/volttron:tcc
    container_name: central
    ports:
      # host_port:container_port
      # ssl port for web
      - 8441:8443
      # port for VIP-address
      - 22911:22916
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
    volumes:
      - ./platform_configs/central:/home/volttron/configs
      - ./platform_configs/central/central_platform_config.yml:/platform_config.yml

#      - ./transactivecontrol/TNS/:/home/volttron/volttron/config/
#      - ./log/:/home/volttron/volttron/log
#      - ./upgrade-scripts:/home/volttron/volttron/upgrade-scripts
#      - ./volttron-GS/:/home/volttron/volttron/transactivecontrol
#      - ./source/bcvtb:/home/volttron/volttron/bcvtb
#    build:
#      context: .
#      args:
#        buildings: campus_city
#    working_dir: /home/volttron/volttron/
#    command: bash upgrade-scripts/upgrade-tns