version: '3.4'

# extension fields to make this yaml DRY; see https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-volttron: &default-depends
  depends_on:
    - central

x-default-image: &default-image
  image: eclipsevolttron/volttron:tcc-ecolong-local

x-env: &default-env
  environment:
    - CONFIG=/home/volttron/configs
    - LOCAL_USER_ID=1000
    - LOG_PREFIX=volttron-log-setup

services:
  building1:
    <<: *default-depends
    <<: *default-image
    <<: *default-env
    container_name: building1
    hostname: building1
    networks:
      tcc_network:
        ipv4_address: 172.28.5.1
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22911:22916
      # ssl port for web
      - 8441:8443
    volumes:
      - ./platform_configs/building1/agent_configs:/home/volttron/configs
      - ./platform_configs/building1/building1_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./logs:/home/volttron/logs
      - building1-volume:/home/volttron/db
      - ./source/eplus/building1:/home/volttron/building1

  smalloffice:
    <<: *default-depends
    <<: *default-image
    <<: *default-env
    container_name: smalloffice
    hostname: smalloffice
    networks:
      tcc_network:
        ipv4_address: 172.28.5.2
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22912:22916
      # ssl port for web
      - 8442:8443
    volumes:
      - ./platform_configs/smalloffice/agent_configs:/home/volttron/configs
      - ./platform_configs/smalloffice/smalloffice_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./logs:/home/volttron/logs
      - smalloffice-volume:/home/volttron/db/
      - ./source/eplus/smalloffice:/home/volttron/smalloffice

  largeoffice:
    <<: *default-depends
    <<: *default-image
    <<: *default-env
    container_name: largeoffice
    hostname: largeoffice
    networks:
      tcc_network:
        ipv4_address: 172.28.5.3
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22913:22916
      # ssl port for web
      - 8443:8443
    volumes:
      - ./platform_configs/largeoffice/agent_configs:/home/volttron/configs
      - ./platform_configs/largeoffice/largeoffice_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./logs:/home/volttron/logs
      - largeoffice-volume:/home/volttron/db/
      - ./source/eplus/largeoffice:/home/volttron/largeoffice

  brsw:
    <<: *default-depends
    <<: *default-image
    <<: *default-env
    container_name: brsw
    hostname: brsw
    networks:
      tcc_network:
        ipv4_address: 172.28.5.4
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22914:22916
      # ssl port for web
      - 8444:8443
    volumes:
      - ./platform_configs/brsw/agent_configs:/home/volttron/configs
      - ./platform_configs/brsw/brsw_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./logs:/home/volttron/logs
      - brsw-volume:/home/volttron/db/
      - ./source/eplus/brsw:/home/volttron/brsw

  central:
    build: .
    <<: *default-image
    <<: *default-env
    container_name: central
    hostname: central
    networks:
      tcc_network:
        ipv4_address: 172.28.5.5
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22915:22916
      # ssl port for web
      - 8445:8443
    volumes:
      - ./platform_configs/central/agent_configs:/home/volttron/configs
      - ./platform_configs/central/central_platform_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./logs:/home/volttron/logs
      - central-volume:/home/volttron/db

networks:
  tcc_network:
    name: tcc_network
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         ip_range: 172.28.5.0/24

volumes:
  building1-volume:
    name: building1-data
  smalloffice-volume:
    name: smalloffice-data
  largeoffice-volume:
    name: largeoffice-data
  brsw-volume:
    name: brsw-data
  central-volume:
    name: central-data
