version: '3.4'

services:
  building1:
    image: volttron/volttron:tcc-dev
    depends_on:
      - central
    container_name: building1
    hostname: building1
    networks:
      tcc_network:
        ipv4_address: 172.28.5.1
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22911:22916
      # ssl port for web
      - 8441:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
      - LOG_PREFIX=building1-setup
    volumes:
      - ./platform_configs/building1/agent_configs:/home/volttron/configs
      - ./platform_configs/building1/building1_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./log:/home/volttron/logs
      - ./core:/startup


  smalloffice:
    image: volttron/volttron:tcc-dev
    depends_on:
      - central
    container_name: smalloffice
    hostname: smalloffice
    networks:
      tcc_network:
        ipv4_address: 172.28.5.2
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22912:22916
      # ssl port for web
      - 8442:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
      - LOG_PREFIX=smalloffice-setup
    volumes:
      - ./platform_configs/smalloffice/agent_configs:/home/volttron/configs
      - ./platform_configs/smalloffice/smalloffice_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./log:/home/volttron/logs
      - ./core:/startup

  largeoffice:
    image: volttron/volttron:tcc-dev
    depends_on:
      - central
    container_name: largeoffice
    hostname: largeoffice
    networks:
      tcc_network:
        ipv4_address: 172.28.5.3
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22913:22916
      # ssl port for web
      - 8443:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
      - LOG_PREFIX=largeoffice-setup
    volumes:
      - ./platform_configs/largeoffice/agent_configs:/home/volttron/configs
      - ./platform_configs/largeoffice/largeoffice_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./log:/home/volttron/logs
      - ./core:/startup

  brsw:
    image: volttron/volttron:tcc-dev
    depends_on:
      - central
    container_name: brsw
    hostname: brsw
    networks:
      tcc_network:
        ipv4_address: 172.28.5.4
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22914:22916
      # ssl port for web
      - 8444:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
      - LOG_PREFIX=brsw-setup
    volumes:
      - ./platform_configs/brsw/agent_configs:/home/volttron/configs
      - ./platform_configs/brsw/brsw_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./log:/home/volttron/logs
      - ./core:/startup

  central:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: volttron/volttron:tcc-dev
    container_name: central
    hostname: central
    networks:
      tcc_network:
        ipv4_address: 172.28.5.5
    ports:
      # host_port:container_port
      # port for VIP-address
      - 22915:22916
      # ssl port for web
      - 8445:8443
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
      - LOG_PREFIX=central-setup
    volumes:
      - ./platform_configs/central/agent_configs:/home/volttron/configs
      - ./platform_configs/central/central_platform_config.yml:/platform_config.yml
      - ./source/bcvtb:/code/volttron/bcvtb
      - ./log:/home/volttron/logs
      - ./core:/startup

networks:
  tcc_network:
    name: tcc_network
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         ip_range: 172.28.5.0/24
