# Properties to be added to the root config file
# the properties should be ingestible for volttron
# the values will be presented in the config file
# as key=value
config:
  vip-address: tcp://172.28.5.1:22911
  bind-web-address: http://172.28.5.1:8441
  instance-name: building1
  message-bus: zmq

# Agents dictionary to install.  The key must be a valid
# identity for the agent to be installed correctly.
agents:

  # Each agent identity.config file should be in the configs
  # directory and will be used to install the agent.
  platform.historian:
    source: $VOLTTRON_ROOT/services/core/SQLHistorian
    config: $CONFIG/sqlhistorian.config
    tag: sqlite-db

  listener:
    source: $VOLTTRON_ROOT/examples/ListenerAgent
    config: $CONFIG/listener.config
    tag: listener

  # TODO: add rest of ahu1-4 vavs
  platform.vav102:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/102_CLGSETP.config
    tag: vav

  platform.vav118:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/118_CLGSETP.config
    tag: vav

  platform.vav119:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/119_CLGSETP.config
    tag: vav

  platform.vav120:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/120_CLGSETP.config
    tag: vav

  platform.vav121:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/121_CLGSETP.config
    tag: vav

  platform.vav123a:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/123a_CLGSETP.config
    tag: vav

  platform.vav123b:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/123b_CLGSETP.config
    tag: vav

  platform.vav127a:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/127a_CLGSETP.config
    tag: vav

  platform.vav127b:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/127b_CLGSETP.config
    tag: vav

  platform.vav129:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/129_CLGSETP.config
    tag: vav

  platform.vav131:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/131_CLGSETP.config
    tag: vav

  platform.vav133:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/133_CLGSETP.config
    tag: vav

  platform.vav136:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/136_CLGSETP.config
    tag: vav

  platform.vav142:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/142_CLGSETP.config
    tag: vav

  platform.vav143:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/143_CLGSETP.config
    tag: vav

  platform.vav150:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/VAVAgent
    config: $CONFIG/150_CLGSETP.config
    tag: vav

  platform.ahu1:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/AHUAgent
    config: $CONFIG/AHU1.config
    tag: ahu

  platform.ahu2:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/AHUAgent
    config: $CONFIG/AHU2.config
    tag: ahu

  platform.ahu3:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/AHUAgent
    config: $CONFIG/AHU3.config
    tag: ahu

  platform.ahu4:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/AHUAgent
    config: $CONFIG/AHU4.config
    tag: ahu

  # TODO: add rest of light agents
  platform.light129:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/LightingAgent
    config: $CONFIG/129_LIGHT.config
    tag: light

  platform.uncontrol_load:
    source: $VOLTTRON_ROOT/volttron/MarketAgents/UnControlLoadAgent
    config: $CONFIG/uncontrol_load.config
    tag: uncontrol_load

  platform.market:
    source: $VOLTTRON_ROOT/volttron/MixMarketServiceAgent
    config: $VOLTTRON_ROOT/volttron/MixMarketServiceAgent/config
    tag: market-service

  tns.building_agent:
    source: $VOLTTRON_ROOT/volttron/TNS_building_Agent
    config: $CONFIG/BUILDING1.config
    tag: tns_building

  platform.actuator:
    source: $VOLTTRON_ROOT/volttron/pnnl/energyplusagent
    config: $CONFIG/ep_building1.config
    tag: eplus

  forwarder.tns_pnnl:
    source: $VOLTTRON_ROOT/services/core/ForwardHistorian
    config: $CONFIG/forwarder.config
    tag: forwarder
#    priority: 10 # setting at 10 instead of using default 50 results in a failed build


