# Properties to be added to the root config file
# the properties should be ingestible for volttron
# the values will be presented in the config file
# as key=value
config:
  vip-address: tcp://172.28.5.5:22915
  bind-web-address: http://172.28.5.5:8445
  instance-name: central
  message-bus: zmq

# Agents dictionary to install.  The key must be a valid
# identity for the agent to be installed correctly.
agents:

  # Each agent identity.config file should be in the configs
  # directory and will be used to install the agent.
  platform.historian:
    source: $VOLTTRON_ROOT/services/core/SQLHistorian
    config: $CONFIG/sqlhistorian.config
    tag: sqlite-db

  listener:
    source: $VOLTTRON_ROOT/examples/ListenerAgent
    config: $CONFIG/listener.config
    tag: listener

  # TODO: add rest of forwarders: . upgrade-scripts/campus_city/upgrade-b1-forwarder
    #. upgrade-scripts/campus_city/upgrade-so-forwarder
    #. upgrade-scripts/campus_city/upgrade-brsw-forwarder
  forwarder.tns_sim_lo:
    source: $VOLTTRON_ROOT/services/core/ForwardHistorian
    config: $CONFIG/lo-forwarder.config
    tag: forwarder

  tns.campus:
    source: $VOLTTRON_ROOT/volttron/TNS_campus_Agent
    config: $CONFIG/tns_campus.config
    tag: tns_campus

  tns.city:
    source: $VOLTTRON_ROOT/volttron/TNS_city_Agent
    config: $CONFIG/tns_city.config
    tag: tns_city


