name: Test image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # The strategy allows customization of the build and allows matrixing the version of os and software
    # https://docs.github.com/en/free-pro-team@l.atest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        # Each entry in the os and python-version matrix will be run so 2 os x 4 python-versions will result in 8 jobs run
        os: [ ubuntu-18.04 ]
        python-version: [ 3.6, 3.7, 3.8 ]

    runs-on: ${{ matrix.os }}

    steps:
        - uses: actions/checkout@v2
        - name: Code cleanup
          run: |
            pip install pre-commit
            pre-commit run --all-files
        - name: Run integration tests
          run: ./run-test-docker-image.sh -w 360
          # After numerous test runs, it appears that the server on GitHub Actions takes about 6 minutes (360 seconds) to complete the Volttron setup;
          # if the tests start running less than 6 minutes after the container is being created, we might exec into the container before it starts running,
          # thereby causing the tests to fail because the container isn't running.
